version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@0x/sol-profiler"
    versions:
    - 4.1.14
    - 4.1.21
    - 4.1.22
    - 4.1.23
    - 4.1.24
  - dependency-name: "@0x/sol-trace"
    versions:
    - 3.0.27
    - 3.0.29
    - 3.0.31
    - 3.0.32
    - 3.0.33
  - dependency-name: "@0x/sol-coverage"
    versions:
    - 4.0.27
    - 4.0.29
    - 4.0.31
    - 4.0.32
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.1
  - dependency-name: react-dev-utils
    versions:
    - 11.0.1
    - 11.0.2
  - dependency-name: got
    versions:
    - 11.8.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
