version: 2.0

jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.15.3
            - image: trufflesuite/ganache-cli:v6.4.1
        steps:
            - checkout
            - run:
                name: "Update NPM"
                command: sudo npm install -g npm@6.7.0
            - run:
                name: "Bootstrap Monorepo"
                command: |
                  npm install
                  npm run bootstrap
            - run:
                name: "Build Packages"
                command: ./node_modules/.bin/lerna run build
            - save_cache:
                key: repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ~/repo
    lint:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.15.3
        steps:
            - restore_cache:
                keys:
                    - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: "Lint Packages"
                command: ./node_modules/.bin/lerna run lint
    test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.15.3
            - image: trufflesuite/ganache-cli:v6.4.1
              command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
        steps:
            - restore_cache:
                keys: 
                    - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: "Test Packages"
                command: ./node_modules/.bin/lerna run test
    coverage:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10.15.3
            - image: trufflesuite/ganache-cli:v6.4.1
              command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
        steps:
            - restore_cache:
                keys: 
                    - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: "Cover Packages"
                command: ./node_modules/.bin/lerna run coverage
workflows:
    version: 2
    main:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: gh-pages
            - lint:
                requires:
                    - build
                filters:
                    branches:
                        ignore: gh-pages
            - test:
                requires:
                    - build
                filters:
                    branches:
                        ignore: gh-pages
            - coverage:
                requires:
                    - build
                    - test
                filters:
                    branches:
                        ignore: gh-pages
