version: 2.0

jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:9
        steps:
            - checkout
            - run:
                name: "Update NPM"
                command: sudo npm install -g npm@5.6.0
            - run:
                name: "Install Node Modules"
                command: |
                    npm install
                    ./node_modules/.bin/lerna exec -- npm install
            - run:
                name: "Build Packages"
                command: ./node_modules/.bin/lerna run build
            - run:
                name: "Compile Contracts"
                command: cd packages/contracts && ./node_modules/.bin/truffle compile
            - save_cache:
                key: repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ~/repo
    lint:
        working_directory: ~/repo
        docker:
            - image: circleci/node:9
        steps:
            - restore_cache:
                keys:
                    - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: "Lint Packages"
                command: ./node_modules/.bin/lerna run lint
    test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:9
            - image: trufflesuite/ganache-cli:v6.2.5
              command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
        steps:
            - restore_cache:
                keys: 
                    - repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                name: "Test Packages"
                command: ./node_modules/.bin/lerna run test
workflows:
    version: 2
    main:
        jobs:
            - build
            - lint:
                requires:
                    - build
                filters:
                    branches:
                        ignore: gh-pages
            - test:
                requires:
                    - build
                filters:
                    branches:
                        ignore: gh-pages
