version: 2.0 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/aztec-crypto-js # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:8.11.3
      - image: trufflesuite/ganache-cli
        command: ganache-cli -i 1234 -p 8545 -e 10000000 -l 6721975
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: "Update NPM"
          command: sudo npm install -g npm@5.6.0
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: # weird bug when installing modules otherwise
          name: "Remove Package Lock"
          command: rm -f package-lock.json
      - run: # simply installing the modules
          name: "Install Node Modules"
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # deploy contracts
          name: "Deploy Contracts"
          command: ./node_modules/.bin/truffle migrate --network development
      - run: # run tests
          name: "Test AZTEC"
          command: npm run test
