version: 2.0

jobs:
  build:
    working_directory: ~/AZTEC
    docker:
      - image: circleci/node:10.15.0-browsers
    filters:
      branches:
        only:
          - master
          - develop
    steps:
      - run: npm install
      - run: npm run test
