AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sign a data with trusted private key, so cliend can send it to the GSN later
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        API_KEY_REQUIRED: True
        SIGNER_ADDRESS: "0x0..."
        SIGNER_PRIVATE_KEY: "0x0..."
        SIGNER_GANACHE_ADDRESS: "0x0..."
        SIGNER_GANACHE_PRIVATE_KEY: "0x0..."
        INFURA_PROJECT_KEY: "infuraApiKeyHere"
        DB_HOST: ""
        DB_PORT: "5432"
        DB_DATABASE_PREFIX: ""
        DB_USER: ""
        DB_PASSWORD: ""
        MAIN_AZTECAccountRegistryGSN: ""
        ROPSTEN_AZTECAccountRegistryGSN: ""
        RINKEBY_AZTECAccountRegistryGSN: ""
        GOERLI_AZTECAccountRegistryGSN: ""
        KOVAN_AZTECAccountRegistryGSN: ""
  Api:
    Cors:
      AllowMethods: '''OPTIONS,POST,GET'''
      AllowHeaders: '''Content-Type'''
      AllowOrigin: '''*'''

Resources:
  SignTxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./signerFunction
      Handler: app.signTxHandler
      Runtime: nodejs10.x
      FunctionName: sign-tx
      Role: arn:aws:iam::HERE-SOME-ID:role/HERE-YOUR-ROLE
      Events:
        SignTx:
          Type: Api
          Properties:
            Path: /{networkId}/{apiKey}
            Method: post
  HasFreeTransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./signerFunction
      Handler: balance.balanceHandler
      Runtime: nodejs10.x
      FunctionName: has-free-txs
      Role: arn:aws:iam::HERE-SOME-ID:role/HERE-YOUR-ROLE
      Events:
        SignTx:
          Type: Api
          Properties:
            Path: /{networkId}/{apiKey}
            Method: get
  MigrateDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./signerFunction
      Handler: migrate.migrationHandler
      Runtime: nodejs10.x
      FunctionName: migrate-db
      Role: arn:aws:iam::HERE-SOME-ID:role/HERE-YOUR-ROLE
      # SecurityGroupIds: 
      #   - String
      # SubnetIds: 
      #   - String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SignTxApi:
    Description: "API Gateway endpoint URL for SignTx function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/{networkId}/{apiKey}/"
  SignTxFunction:
    Description: "SignTx Lambda Function ARN"
    Value: !GetAtt SignTxFunction.Arn
  SignTxFunctionIamRole:
    Description: "Implicit IAM Role created for SignTx function"
    Value: !GetAtt SignTxFunction.Arn
  HasFreeTransactionsApi:
    Description: "API Gateway endpoint URL for HasFreeTransactions function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/{networkId}/{apiKey}/"
  HasFreeTransactionsFunction:
    Description: "SignTx Lambda Function ARN"
    Value: !GetAtt HasFreeTransactionsFunction.Arn
  MigrateDBFunction:
    Description: "MigrateDB Lambda Function ARN"
    Value: !GetAtt MigrateDBFunction.Arn
